# Generated by Django 5.0.4 on 2024-10-29 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usafa',
            fields=[
                ('id_usafa', models.AutoField(primary_key=True, serialize=False)),
                ('nome_usafa', models.CharField(max_length=255)),
                ('endereco_usafa_rua', models.CharField(max_length=255)),
                ('endereco_usafa_numero', models.IntegerField()),
                ('endereco_usafa_complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('endereco_usafa_bairro', models.CharField(max_length=255)),
                ('endereco_usafa_cidade', models.CharField(max_length=255)),
                ('endereco_usafa_estado', models.CharField(max_length=255)),
                ('CEP_usafa', models.IntegerField()),
            ],
            options={
                'db_table': 'USAFA',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('CPF', models.CharField(max_length=255)),
                ('RG', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('CEP', models.IntegerField()),
                ('endereco_usuario_rua', models.CharField(max_length=255)),
                ('endereco_usuario_numero', models.IntegerField()),
                ('endereco_usuario_complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('endereco_usuario_bairro', models.CharField(max_length=255)),
                ('endereco_usuario_cidade', models.CharField(max_length=255)),
                ('endereco_usuario_estado', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('usafa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='protoDigital.usafa')),
            ],
            options={
                'db_table': 'USUARIO',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('tipo_consulta', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='protoDigital.usuario')),
            ],
            options={
                'db_table': 'CONSULTA',
            },
        ),
    ]
