# Generated by Django 5.1.2 on 2024-11-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protoDigital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nome_usuario',
            field=models.CharField(default='meu_valor', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(default='2024-01-01', max_length=255),
            preserve_default=False,
        ),
    ]
