# Generated by Django 5.1.2 on 2024-11-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protoDigital', '0002_usuario_nome_usuario_usuario_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(blank=True, default='123456', max_length=128, null=True),
        ),
    ]
